### PR TITLE
Fix the dag

### PR DESCRIPTION
**Pull request by leahcornelius**
In reference to PR #15

### CODE REVIEW

**Comment by TheDevMinerTV** [comment]
I will go over spelling in a few hours, expect a commit :)

**Comment by leahcornelius** [comment]
@TheDevMinerTV  Awesome thanks

**Comment by leahcornelius** [comment]
Nice one thanks @TheDevMinerTV

**Comment by leahcornelius** [comment]
Combined with #14 into #26, please move any discussion there

**Pull request closed without merging**
